/* This is generated code, do not change this file manually.             */
/*                                                                       */
/* To change these definitions, alter road-colors.yml and run:           */
/*                                                                       */
/*   ./scripts/generate_road_colors.py | tee road-colors-generated.mss   */
/*                                                                       */
@bridleway-fill: #ff1700;
@cycle-case: @land;
@cycle-fill: #0000ff;
@footway-fill: #007200;
@icn-overlay: #ff00ff;
@icn-shield-fill: #f6f6f6;
@lcn-overlay: #0000ff;
@lcn-shield-fill: #f6f6f6;
@motorway-case: #f6f6f6;
@motorway-fill: #c0ccc4;
@motorway-line: #f6f6f6;
@motorway-shield-fill: #620728;
@mtb-overlay: #ff6200;
@mtb-shield-fill: #f6f6f6;
@ncn-overlay: #aa00ff;
@ncn-shield-fill: #f6f6f6;
@path-fill: #873100;
@pedestrian-case: @land;
@pedestrian-fill: #007200;
@primary-case: #d8b267;
@primary-fill: #f4dfc3;
@primary-line: #f4dfc3;
@primary-shield-fill: #4c2e00;
@rail-line: #999999;
@rcn-overlay: #5500ff;
@rcn-shield-fill: #f6f6f6;
@secondary-case: #b1bb5d;
@secondary-fill: #f6f8d2;
@secondary-line: #f6f8d2;
@secondary-shield-fill: #323b00;
@speed20-fill: #4bffff;
@speed32-fill: #b0ffff;
@standard-case: #c8c8c8;
@standard-fill: #f6f6f6;
@standard-line: #f6f6f6;
@steps-case: @land;
@steps-fill: #003e00;
@tertiary-case: #686868;
@tertiary-fill: #f6f6f6;
@tertiary-line: #f6f6f6;
@tertiary-shield-fill: #3b3b3b;
@trunk-case: #f6f6f6;
@trunk-fill: #c0ccc4;
@trunk-line: #f6f6f6;
@trunk-shield-fill: #5d1b0b;
