/* This is generated code, do not change this file manually.             */
/*                                                                       */
/* To change these definitions, alter road-colors.yml and run:           */
/*                                                                       */
/*   ./scripts/generate_road_colors.py | tee road-colors-generated.mss   */
/*                                                                       */
@cycle-case: @land;
@cycle-fill: #0000ff;
@cycle-line: @standard_line;
@icn-overlay: #0b910b;
@icn-shield-fill: #f6f6f6;
@lcn-overlay: #0000ff;
@lcn-shield-fill: #f6f6f6;
@motorway-case: #f6f6f6;
@motorway-fill: #c0ccc4;
@motorway-line: #f6f6f6;
@motorway-shield-fill: #620728;
@ncn-overlay: #ff0000;
@ncn-shield-fill: #f6f6f6;
@pedestrian-case: @land;
@pedestrian-fill: #ff0000;
@pedestrian-line: @standard_line;
@primary-case: #c0ccc4;
@primary-fill: #f6f6f6;
@primary-line: #c0ccc4;
@primary-shield-fill: #4c2e00;
@rail-line: #999999;
@rcn-overlay: #b42dff;
@rcn-shield-fill: #f6f6f6;
@secondary-case: #c0ccc4;
@secondary-fill: #f6f6f6;
@secondary-line: #c0ccc4;
@secondary-shield-fill: #323b00;
@standard-case: #f6f6f6;
@standard-fill: #f6f6f6;
@standard-line: #f6f6f6;
@steps-case: @land;
@steps-fill: #9a2a00;
@tertiary-shield-fill: #3b3b3b;
@trunk-case: #f6f6f6;
@trunk-fill: #c0ccc4;
@trunk-line: #f6f6f6;
@trunk-shield-fill: #5d1b0b;
